import { createServer } from 'node:http';
import { createHash, randomBytes } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';

const port = Number(process.env.PORT || 8000);
const root = process.cwd();
const sessions = new Map();
const oauthStates = new Map();
const mimeTypes = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.webmanifest': 'application/manifest+json; charset=utf-8' };
const integrations = {
  slack: { clientId: process.env.SLACK_CLIENT_ID, clientSecret: process.env.SLACK_CLIENT_SECRET, authorize: 'https://slack.com/oauth/v2/authorize', token: 'https://slack.com/api/oauth.v2.access', scopes: 'channels:history,groups:history,im:history,mpim:history,users:read' },
  linear: { clientId: process.env.LINEAR_CLIENT_ID, clientSecret: process.env.LINEAR_CLIENT_SECRET, authorize: 'https://linear.app/oauth/authorize', token: 'https://api.linear.app/oauth/token', scopes: 'read' },
};
function cookies(request) { return Object.fromEntries((request.headers.cookie || '').split(';').filter(Boolean).map(item => item.trim().split('='))); }
function session(request, response) { let id = cookies(request).relay_session; if (!id || !sessions.has(id)) { id = randomBytes(24).toString('hex'); sessions.set(id, { integrations: {}, tokens: {} }); response.setHeader('Set-Cookie', `relay_session=${id}; HttpOnly; SameSite=Lax; Path=/`); } return [id, sessions.get(id)]; }
function redirect(response, path) { response.writeHead(302, { Location: path }); response.end(); }
function json(response, status, body) { response.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); response.end(JSON.stringify(body)); }
function baseUrl(request) { return `${request.headers['x-forwarded-proto'] || 'http'}://${request.headers.host}`; }
function errorPage(response, message) { response.writeHead(400, { 'Content-Type': 'text/html; charset=utf-8' }); response.end(`<!doctype html><title>Relay connection error</title><body style="font-family:system-ui;padding:40px;background:#111a1b;color:#edf1e9"><h1>Relay could not finish that connection.</h1><p>${message}</p><p><a style="color:#f0ab62" href="/">Return to Relay</a></p></body>`); }
async function identity(provider, accessToken) { if (provider === 'slack') { const response = await fetch('https://slack.com/api/auth.test', { headers: { Authorization: `Bearer ${accessToken}` } }); const data = await response.json(); return { name: data.team || 'Slack workspace', detail: data.user || '' }; }
  const response = await fetch('https://api.linear.app/graphql', { method: 'POST', headers: { Authorization: accessToken, 'Content-Type': 'application/json' }, body: JSON.stringify({ query: '{ viewer { name organization { name } } }' }) }); const data = await response.json(); return { name: data.data?.viewer?.organization?.name || 'Linear workspace', detail: data.data?.viewer?.name || '' }; }
async function handleOAuth(provider, request, response, url) { const config = integrations[provider]; const [, activeSession] = session(request, response); if (!config?.clientId || !config?.clientSecret) return errorPage(response, `${provider === 'slack' ? 'Slack' : 'Linear'} credentials are not configured on this Relay server.`);
  if (!url.pathname.endsWith('/callback')) { const state = randomBytes(24).toString('hex'); oauthStates.set(state, { provider, session: activeSession, expires: Date.now() + 600000 }); const params = new URLSearchParams({ client_id: config.clientId, redirect_uri: `${baseUrl(request)}/auth/${provider}/callback`, response_type: 'code', scope: config.scopes, state }); return redirect(response, `${config.authorize}?${params}`); }
  const state = oauthStates.get(url.searchParams.get('state')); oauthStates.delete(url.searchParams.get('state')); if (!state || state.provider !== provider || state.expires < Date.now()) return errorPage(response, 'The connection request expired. Please try again from Relay.'); if (url.searchParams.get('error')) return errorPage(response, `The provider declined the connection: ${url.searchParams.get('error')}.`);
  const body = new URLSearchParams({ client_id: config.clientId, client_secret: config.clientSecret, code: url.searchParams.get('code') || '', redirect_uri: `${baseUrl(request)}/auth/${provider}/callback`, grant_type: 'authorization_code' }); const tokenResponse = await fetch(config.token, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded', Accept: 'application/json' }, body }); const tokenData = await tokenResponse.json(); const accessToken = tokenData.access_token || tokenData.authed_user?.access_token; if (!tokenResponse.ok || !accessToken) return errorPage(response, 'The provider did not return an access token. Check the app credentials and redirect URL.'); const profile = await identity(provider, accessToken); state.session.tokens[provider] = accessToken; state.session.integrations[provider] = { name: profile.name, detail: profile.detail, connectedAt: new Date().toISOString(), tokenHash: createHash('sha256').update(accessToken).digest('hex').slice(0, 12) }; return redirect(response, '/?connected=' + provider); }
async function staticFile(request, response, pathname) { const safePath = normalize(pathname === '/' ? '/index.html' : pathname).replace(/^[/\\]+/, ''); const file = join(root, safePath); if (!file.startsWith(root)) return json(response, 403, { error: 'Forbidden' }); try { const content = await readFile(file); response.writeHead(200, { 'Content-Type': mimeTypes[extname(file)] || 'application/octet-stream' }); response.end(content); } catch { json(response, 404, { error: 'Not found' }); } }
createServer(async (request, response) => { const url = new URL(request.url, baseUrl(request)); try { if (url.pathname === '/api/integrations') { const [, current] = session(request, response); return json(response, 200, { integrations: Object.fromEntries(Object.entries(current.integrations).map(([key, value]) => [key, { ...value, configured: Boolean(integrations[key]?.clientId) }])) }); } if (url.pathname.startsWith('/auth/')) { const [, provider] = url.pathname.split('/').filter(Boolean); return handleOAuth(provider, request, response, url); } return staticFile(request, response, url.pathname); } catch (error) { console.error(error); return json(response, 500, { error: 'Relay server error' }); } }).listen(port, () => console.log(`Relay is running at http://localhost:${port}`));
